#! /bin/bash

## Authors: Francisco J. Romero-Campero
##          Ana Belen Romero-Losada
## Contact: Francisco J. Romero-Campero - fran@us.es

## Load parameters from file

## Input file name
PARAMS=$1

echo "Loading parameters from file " $PARAMS " ... "

## Load installation directory
INS_DIR=$(grep installation_directory: $PARAMS | awk '{ print $2 }')
## Load working directory
WD=$(grep working_directory: $PARAMS | awk '{ print $2 }')
## Load main folder
MAIN_FOLDER=$(grep main_folder: $PARAMS | awk '{ print $2 }')
## Load number of samples
NUM_SAMPLES=$(grep number_of_samples: $PARAMS | awk '{ print $2 }')
## Load microalgae
MICROALGAE=$(grep microalgae: $PARAMS | awk '{ print $2 }')
## Load accession numbers for each sample
ACC_SAMPLES=()
for i in `seq 0 $((${NUM_SAMPLES} - 1))`
do   
   ACC_SAMPLES[$i]=$(grep acc_sample$(($i +1)): $PARAMS | awk '{ print $2 }')
done
## Load control condition name
CONTROL_COND=$(grep control_condition_name: $PARAMS | awk '{ print $2 }')
## Load experimental condition name
EXPERIMENTAL_COND=$(grep experimental_condition_name: $PARAMS | awk '{ print $2 }')
## Load experimental design consisting of sample conditions
EXPERIMENTAL_DESIGN=()
for i in `seq 0 $((${NUM_SAMPLES} - 1))`
do
   EXPERIMENTAL_DESIGN[$i]=$(grep condition_sample$(($i + 1)) $PARAMS | awk '{ print $2 }')
done 

echo "The following parameters were loaded."
echo " - Installation directory: " $INS_DIR
echo " - Working directory: " $WD
echo " - Main folder: " $MAIN_FOLDER
echo " - Number of samples: " $NUM_SAMPLES
echo " - Microalgae: " $MICROALGAE
echo " - Sample accession numbers: " ${ACC_SAMPLES[@]}
echo " - Control condition name: " ${CONTROL_COND}
echo " - Experimental condition name: " ${EXPERIMENTAL_COND} 
echo " - Experimental design: " ${EXPERIMENTAL_DESIGN[@]}
echo " "

echo "Generating working directory."
## Access working directory
cd $WD

## Create and access main folder
mkdir ${MAIN_FOLDER}
cd ${MAIN_FOLDER}

## Create subfolders
mkdir samples results logs

## Create folder for each sample
cd samples

for i in `seq 1 ${NUM_SAMPLES}`
do
   mkdir sample_$i
done
echo "Working directory generated"
echo " "

## Create experimental design file
cd $WD/${MAIN_FOLDER}/samples

echo "sample,condition" > experimental_design.csv
for i in `seq 0 $((${NUM_SAMPLES} -1))`
do
   echo "sample"_$(($i + 1)),${EXPERIMENTAL_DESIGN[$i]} >> experimental_design.csv
done

## Parallel sample processing
echo "Parallel sample processing"
for  i in `seq 0 $((${NUM_SAMPLES} - 1))`
do
   echo "- Sample " $(($i + 1)) " processing submitted to queue"
   qsub -o $WD/${MAIN_FOLDER}/logs/${ACC_SAMPLES[$i]} ${INS_DIR}/scripts/sample_processing.sh $WD/${MAIN_FOLDER}/samples/sample_$(($i +1)) ${ACC_SAMPLES[$i]} ${INS_DIR}/data/${MICROALGAE}/genome/hisat2_index_${MICROALGAE} ${INS_DIR}/data/${MICROALGAE}/annotation/${MICROALGAE}.gtf ${NUM_SAMPLES} ${INS_DIR} $WD/${MAIN_FOLDER}
done
