#! /bin/bash

## Authors: Francisco J. Romero-Campero
##          Ana Belen Romero-Losada
## Contact: Francisco J. Romero-Campero - fran@us.es

## Load parameters from file

## Input file name
PARAMS=$1

echo "                   ^^^^^^^^^^^                           "
echo "                  &&&.=====.&&&                          "
echo "                 &&&&  6  6 &&&&                         "
echo "                &&&&         &&&&                        "
echo "                &&&&\  \__/ /&&&&                        "
echo "                     \_____/                             "
echo " _____________OOOO_____|_|___________________________    "
echo "/                                                    \   "
echo "|             WELCOME TO OUR TOOL                    |   "
echo "| MARACAS (MicroAlgae RnA-seq and Chip-seq AnalysiS) |   "
echo "|     This is the RNA-seq Data Analysis Pipeline     |   "
echo "|    Specifically Design to Support the Microalgae   |   "
echo "|      Resarch Community to Exploit Omics Data       |   "
echo "|                                                    |   "
echo "|        Ubuntu means I am because we are            |   "
echo "|           Nelson Mandela (1918 - 2013)             |   "     
echo "\_______________________________OOOO_________________/   "
echo "                   /    |    \                           "
echo "                   |    |    |                           "
echo "                   /    |    \                           "
echo "                  /     |     \                          "
echo "                  |_____|_____|                          "
echo "                     /  X  \                             "
echo "                    (__/ \__)                            "
echo ""
echo ""


echo "Loading parameters from file " $PARAMS " ... "

## Load installation directory
INS_DIR=$(grep installation_directory: $PARAMS | awk '{ print $2 }')

## Load working directory
WD=$(grep working_directory: $PARAMS | awk '{ print $2 }')

## Load main folder
MAIN_FOLDER=$(grep main_folder: $PARAMS | awk '{ print $2 }')

## Load number of samples
NUM_SAMPLES=$(grep number_of_samples: $PARAMS | awk '{ print $2 }')

## Load microalgae
MICROALGAE=$(grep microalgae: $PARAMS | awk '{ print $2 }')

## Load data source
DATA=$(grep data_source: $PARAMS | awk '{print $2}')

## Load paired end data
PAIRED=$(grep paired_end: $PARAMS | awk '{print $2}')

## Load accession numbers for each sample o file location depending on data source
if [ $DATA == "DB" ]
then
	ACC_SAMPLES=()
	for i in `seq 0 $((${NUM_SAMPLES} - 1))`
	do   
   	ACC_SAMPLES[$i]=$(grep acc_sample$(($i +1)): $PARAMS | awk '{ print $2 }')
	done
elif [ $DATA == "FILES" ] && [ $PAIRED == "FALSE" ]
then
	LOC_SAMPLES=()
	for i in `seq 0 $((${NUM_SAMPLES} - 1))`
	do   
   	LOC_SAMPLES[$i]=$(grep loc_sample$(($i +1)): $PARAMS | awk '{ print $2 }')
		ACC_SAMPLES[$i]=sample$(($i+1))
	done
elif [ $DATA == "FILES" ] && [ $PAIRED == "TRUE" ]
then
	LOC_SAMPLES_LEFT=()
	LOC_SAMPLES_RIGHT=()
	for i in `seq 0 $((${NUM_SAMPLES} - 1))`
	do   
   	LOC_SAMPLES_LEFT[$i]=$(grep loc_sample_left$(($i +1)): $PARAMS | awk '{ print $2 }')
   	LOC_SAMPLES_RIGHT[$i]=$(grep loc_sample_right$(($i +1)): $PARAMS | awk '{ print $2 }')
		ACC_SAMPLES[$i]=sample$(($i+1))
	done
fi

## Load control condition name
CONTROL_COND=$(grep control_condition_name: $PARAMS | awk '{ print $2 }')
## Load experimental condition name
EXPERIMENTAL_COND=$(grep experimental_condition_name: $PARAMS | awk '{ print $2 }')
## Load experimental design consisting of sample conditions
EXPERIMENTAL_DESIGN=()
for i in `seq 0 $((${NUM_SAMPLES} - 1))`
do
   EXPERIMENTAL_DESIGN[$i]=$(grep condition_sample$(($i + 1)): $PARAMS | awk '{ print $2 }')
done 
## Load parameters for differential analysis
FOLD_CHANGE=$(grep fold_change: $PARAMS | awk '{ print $2 }')
Q_VALUE=$(grep q_value: $PARAMS | awk '{ print $2 }')

## Load parameter to indicate if the pipeline is going to be run on a cluster or single computer
ARCH=$(grep cluster: $PARAMS | awk '{ print $2}')

## Load parameter with the number of processors
NPROC=$(grep number_processors: $PARAMS | awk '{ print $2}')

echo "The following parameters were loaded."
echo " - Installation directory: " $INS_DIR
echo " - Architecture: " $ARCH
echo " - Number of processors: " $NPROC
echo " - Working directory: " $WD
echo " - Main folder: " $MAIN_FOLDER
echo " - Number of samples: " $NUM_SAMPLES
echo " - Microalgae: " $MICROALGAE

if [ $DATA == "BD" ]
then
	echo " - Sample accession numbers: " ${ACC_SAMPLES[@]}
else
	echo " - Sample locations: " ${LOC_SAMPLES_LEFT[@]}
        echo ${LOC_SAMPLES_RIGHT[@]}
fi

echo " - Control condition name: " ${CONTROL_COND}
echo " - Experimental condition name: " ${EXPERIMENTAL_COND} 
echo " - Experimental design: " ${EXPERIMENTAL_DESIGN[@]}
echo " "

echo "Generating working directory."
## Access working directory
cd $WD

## Create and access main folder
mkdir ${MAIN_FOLDER}
cd ${MAIN_FOLDER}

## Create subfolders
mkdir samples results logs

## Create folder for each sample
cd samples

for i in `seq 1 ${NUM_SAMPLES}`
do
   mkdir sample_$i
done
echo "Working directory generated"
echo " "

## Create experimental design file
cd $WD/${MAIN_FOLDER}/samples

echo "sample,condition" > experimental_design.csv
for i in `seq 0 $((${NUM_SAMPLES} -1))`
do
   echo "sample"_$(($i + 1)),${EXPERIMENTAL_DESIGN[$i]} >> experimental_design.csv
done

if [ $ARCH == "SGE" ]
then

   ## Parallel sample processing
   echo "Parallel sample processing"
   for  i in `seq 0 $((${NUM_SAMPLES} - 1))`
      do
         if [ $DATA == "DB" ]
         then
            qsub -o $WD/${MAIN_FOLDER}/logs/${ACC_SAMPLES[$i]} ${INS_DIR}/scripts/sample_processing.sge $DATA $PAIRED \
                                             $WD/${MAIN_FOLDER}/samples/sample_$(($i +1)) \
                                             ${INS_DIR}/data/${MICROALGAE}/genome/hisat2_index_${MICROALGAE} \
                                             ${INS_DIR}/data/${MICROALGAE}/annotation/${MICROALGAE}.gtf \
                                             ${NUM_SAMPLES} \
                                             ${INS_DIR} \
                                             $WD/${MAIN_FOLDER} \
                                             ${CONTROL_COND} \
                                             ${EXPERIMENTAL_COND} \
                                             ${FOLD_CHANGE} \
                                             ${Q_VALUE} \
                                             ${ACC_SAMPLES[$i]} \
                                             $NPROC
	    sleep 30m
         elif [ $DATA == "FILES" ] && [ $PAIRED == "FALSE" ]
         then
            qsub -o $WD/${MAIN_FOLDER}/logs/${ACC_SAMPLES[$i]} ${INS_DIR}/scripts/sample_processing.sge $DATA $PAIRED \
                                             $WD/${MAIN_FOLDER}/samples/sample_$(($i +1)) \
                                             ${INS_DIR}/data/${MICROALGAE}/genome/hisat2_index_${MICROALGAE} \
                                             ${INS_DIR}/data/${MICROALGAE}/annotation/${MICROALGAE}.gtf \
                                             ${NUM_SAMPLES} \
                                             ${INS_DIR} \
                                             $WD/${MAIN_FOLDER} \
                                             ${CONTROL_COND} \
                                             ${EXPERIMENTAL_COND} \
                                             ${FOLD_CHANGE} \
                                             ${Q_VALUE} \
                                             ${LOC_SAMPLES[$i]} \
                                             $NPROC
         elif [ $DATA == "FILES" ] && [ $PAIRED == "TRUE" ]
         then
            qsub -o $WD/${MAIN_FOLDER}/logs/${ACC_SAMPLES[$i]} ${INS_DIR}/scripts/sample_processing.sh $DATA $PAIRED \
                                             $WD/${MAIN_FOLDER}/samples/sample_$(($i +1)) \
                                             ${INS_DIR}/data/${MICROALGAE}/genome/hisat2_index_${MICROALGAE} \
                                             ${INS_DIR}/data/${MICROALGAE}/annotation/${MICROALGAE}.gtf \
                                             ${NUM_SAMPLES} \
                                             ${INS_DIR} \
                                             $WD/${MAIN_FOLDER} \
                                             ${CONTROL_COND} \
                                             ${EXPERIMENTAL_COND} \
                                             ${FOLD_CHANGE} \
                                             ${Q_VALUE} \
                                             ${LOC_SAMPLES_LEFT[$i]} \
                                             ${LOC_SAMPLES_RIGHT[$i]} \
                                             $NPROC
#	    qsub -o $WD/${MAIN_FOLDER}/logs/${ACC_SAMPLES[$i]} ${INS_DIR}/scripts/sample_processing.sh $DATA $PAIRED $WD/${MAIN_FOLDER}/samples/sample_$(($i +1)) ${LOC_SAMPLES[$i]} ${INS_DIR}/data/${MICROALGAE}/genome/hisat2_index_${MICROALGAE} ${INS_DIR}/data/${MICROALGAE}/annotation/${MICROALGAE}.gtf ${NUM_SAMPLES} ${INS_DIR} $WD/${MAIN_FOLDER} ${CONTROL_COND} ${EXPERIMENTAL_COND} ${FOLD_CHANGE} ${Q_VALUE} $DATA
	    sleep 30m
         fi

         echo "- Sample " $(($i + 1)) " processing submitted to queue"
   done

elif [ $ARCH == "SERVER" ]
then

   ## Sequential sample processing
   echo "Sequential sample processing"
   for  i in `seq 0 $((${NUM_SAMPLES} - 1))`
      do
         if [ $DATA == "DB" ]
         then
            bash ${INS_DIR}/scripts/sample_processing.sh $DATA $PAIRED \
                                             $WD/${MAIN_FOLDER}/samples/sample_$(($i +1)) \
                                             ${INS_DIR}/data/${MICROALGAE}/genome/hisat2_index_${MICROALGAE} \
                                             ${INS_DIR}/data/${MICROALGAE}/annotation/${MICROALGAE}.gtf \
                                             ${NUM_SAMPLES} \
                                             ${INS_DIR} \
                                             $WD/${MAIN_FOLDER} \
                                             ${CONTROL_COND} \
                                             ${EXPERIMENTAL_COND} \
                                             ${FOLD_CHANGE} \
                                             ${Q_VALUE} \
                                             ${ACC_SAMPLES[$i]} \
                                             $NPROC
         elif [ $DATA == "FILES" ] && [ $PAIRED == "FALSE" ]
         then
            bash ${INS_DIR}/scripts/sample_processing.sh $DATA $PAIRED \
                                             $WD/${MAIN_FOLDER}/samples/sample_$(($i +1)) \
                                             ${INS_DIR}/data/${MICROALGAE}/genome/hisat2_index_${MICROALGAE} \
                                             ${INS_DIR}/data/${MICROALGAE}/annotation/${MICROALGAE}.gtf \
                                             ${NUM_SAMPLES} \
                                             ${INS_DIR} \
                                             $WD/${MAIN_FOLDER} \
                                             ${CONTROL_COND} \
                                             ${EXPERIMENTAL_COND} \
                                             ${FOLD_CHANGE} \
                                             ${Q_VALUE} \
                                             ${LOC_SAMPLES[$i]} \
                                             $NPROC
         elif [ $DATA == "FILES" ] && [ $PAIRED == "TRUE" ]
         then
            bash ${INS_DIR}/scripts/sample_processing.sh $DATA $PAIRED \
                                             $WD/${MAIN_FOLDER}/samples/sample_$(($i +1)) \
                                             ${INS_DIR}/data/${MICROALGAE}/genome/hisat2_index_${MICROALGAE} \
                                             ${INS_DIR}/data/${MICROALGAE}/annotation/${MICROALGAE}.gtf \
                                             ${NUM_SAMPLES} \
                                             ${INS_DIR} \
                                             $WD/${MAIN_FOLDER} \
                                             ${CONTROL_COND} \
                                             ${EXPERIMENTAL_COND} \
                                             ${FOLD_CHANGE} \
                                             ${Q_VALUE} \
                                             ${LOC_SAMPLES_LEFT[$i]} \
                                             ${LOC_SAMPLES_RIGHT[$i]} \
                                             $NPROC
         fi
   done

   bash ${INS_DIR}/scripts/transcriptome_merging.sh $WD/${MAIN_FOLDER} ${INS_DIR}/data/${MICROALGAE}/annotation/${MICROALGAE}.gtf
   Rscript ${INS_DIR}/scripts/DE_analysis.R $WD/${MAIN_FOLDER}/samples ${CONTROL_COND} ${EXPERIMENTAL_COND} $FOLD_CHANGE $Q_VALUE $MICROALGAE
   Rscript -e "rmarkdown::render('$WD/${MAIN_FOLDER}/results/DE_report.Rmd', 'pdf_document')" 
   Rscript -e "rmarkdown::render('$WD/${MAIN_FOLDER}/results/DE_report.Rmd', 'html_document')" 	
fi
